steps:

- name: 'gcr.io/cloud-builders/docker'
  id: 'builder'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/${PROJECT_ID}/app:$COMMIT_SHA'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'pusher'
  args: 
  - 'push'
  - 'gcr.io/${PROJECT_ID}/app:$COMMIT_SHA'
  waitFor: ['builder']



- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deployer'
  entrypoint: gcloud
  args: 
  - 'run'
  - 'deploy'
  - 'app'
  - '--image'
  - 'gcr.io/${PROJECT_ID}/app:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '8080'
  - '--max-instances'
  - '2'
  env:
  - 'INSTANCE_CONNECTION_NAME=$PROJECT_ID:us-west4:test-nuka-cola'
  - 'DB_USER=$$user'
  - 'DB_PASS=$$db_pass'
  - 'DB_NAME=rookie'
  secretEnv: ['db_pass', 'user']


availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/user/versions/latest
    env: 'user'
  - versionName: projects/$PROJECT_ID/secrets/db_pass/versions/latest
    env: 'db_pass'


substitutions:
  _IMAGE: gcr.io/${PROJECT_ID}/app

images:
- ${_IMAGE}
